[2025-01-16T16:30:03.641+0000] {taskinstance.py:1159} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: finflow_source_data_pipeline.load_to_gcs_bq.load_product_to_temp manual__2025-01-16T16:28:54.683213+00:00 [queued]>
[2025-01-16T16:30:03.769+0000] {taskinstance.py:1159} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: finflow_source_data_pipeline.load_to_gcs_bq.load_product_to_temp manual__2025-01-16T16:28:54.683213+00:00 [queued]>
[2025-01-16T16:30:03.771+0000] {taskinstance.py:1361} INFO - Starting attempt 1 of 1
[2025-01-16T16:30:03.856+0000] {taskinstance.py:1382} INFO - Executing <Task(GCSToBigQueryOperator): load_to_gcs_bq.load_product_to_temp> on 2025-01-16 16:28:54.683213+00:00
[2025-01-16T16:30:03.876+0000] {standard_task_runner.py:57} INFO - Started process 606 to run task
[2025-01-16T16:30:03.902+0000] {standard_task_runner.py:84} INFO - Running: ['***', 'tasks', 'run', 'finflow_source_data_pipeline', 'load_to_gcs_bq.load_product_to_temp', 'manual__2025-01-16T16:28:54.683213+00:00', '--job-id', '1947', '--raw', '--subdir', 'DAGS_FOLDER/finflow.py', '--cfg-path', '/tmp/tmpzrtsutnw']
[2025-01-16T16:30:03.927+0000] {standard_task_runner.py:85} INFO - Job 1947: Subtask load_to_gcs_bq.load_product_to_temp
[2025-01-16T16:30:04.260+0000] {task_command.py:416} INFO - Running <TaskInstance: finflow_source_data_pipeline.load_to_gcs_bq.load_product_to_temp manual__2025-01-16T16:28:54.683213+00:00 [running]> on host e65a9a79c958
[2025-01-16T16:30:04.844+0000] {taskinstance.py:1662} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='finflow_source_data_pipeline' AIRFLOW_CTX_TASK_ID='load_to_gcs_bq.load_product_to_temp' AIRFLOW_CTX_EXECUTION_DATE='2025-01-16T16:28:54.683213+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2025-01-16T16:28:54.683213+00:00'
[2025-01-16T16:30:04.849+0000] {crypto.py:82} WARNING - empty cryptography key - values will not be stored encrypted.
[2025-01-16T16:30:04.854+0000] {connection.py:232} WARNING - Connection schemes (type: google_cloud_platform) shall not contain '_' according to RFC3986.
[2025-01-16T16:30:04.865+0000] {base.py:73} INFO - Using connection ID 'google_cloud_default' for task execution.
[2025-01-16T16:30:04.872+0000] {gcs_to_bigquery.py:376} INFO - Using existing BigQuery table for storing data...
[2025-01-16T16:30:05.420+0000] {gcs_to_bigquery.py:380} INFO - Executing: {'load': {'autodetect': True, 'createDisposition': 'CREATE_IF_NEEDED', 'destinationTable': {'projectId': 'finflow-analytics-production', 'datasetId': 'finflow_data', 'tableId': 'src_products_temp'}, 'sourceFormat': 'PARQUET', 'sourceUris': ['gs://finflow-analytics-data/raw/products/2025-01-16/products.parquet'], 'writeDisposition': 'WRITE_TRUNCATE', 'ignoreUnknownValues': False, 'schema': {'fields': [{'name': 'product_key', 'type': 'INTEGER', 'mode': 'REQUIRED'}, {'name': 'product_id', 'type': 'STRING', 'mode': 'REQUIRED'}, {'name': 'product_name', 'type': 'STRING', 'mode': 'REQUIRED'}, {'name': 'product_category', 'type': 'STRING', 'mode': 'REQUIRED'}, {'name': 'product_subcategory', 'type': 'STRING', 'mode': 'REQUIRED'}, {'name': 'interest_rate', 'type': 'FLOAT', 'mode': 'REQUIRED'}, {'name': 'monthly_fee', 'type': 'FLOAT', 'mode': 'REQUIRED'}, {'name': 'is_active', 'type': 'BOOLEAN', 'mode': 'REQUIRED'}, {'name': 'created_at', 'type': 'TIMESTAMP', 'mode': 'REQUIRED'}, {'name': 'updated_at', 'type': 'TIMESTAMP', 'mode': 'REQUIRED'}, {'name': 'ingestion_timestamp', 'type': 'TIMESTAMP', 'mode': 'REQUIRED'}]}}}
[2025-01-16T16:30:05.443+0000] {bigquery.py:1595} INFO - Inserting job ***_finflow_source_data_pipeline_load_to_gcs_bq_load_product_to_temp_2025_01_16T16_28_54_683213_00_00_e718d0ab748e3f0b01c60dd29d61fd06
[2025-01-16T16:30:07.767+0000] {taskinstance.py:1937} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/providers/google/cloud/transfers/gcs_to_bigquery.py", line 439, in execute
    job.result(timeout=self.result_timeout, retry=self.result_retry)
  File "/home/airflow/.local/lib/python3.8/site-packages/google/cloud/bigquery/job/base.py", line 922, in result
    return super(_AsyncJob, self).result(timeout=timeout, **kwargs)
  File "/home/airflow/.local/lib/python3.8/site-packages/google/api_core/future/polling.py", line 261, in result
    raise self._exception
google.api_core.exceptions.BadRequest: 400 Error while reading data, error message: Invalid timestamp microseconds value 1737044956452825000 of logical type NONE; in column 'created_at' File: gs://finflow-analytics-data/raw/products/2025-01-16/products.parquet
[2025-01-16T16:30:07.789+0000] {taskinstance.py:1400} INFO - Marking task as FAILED. dag_id=finflow_source_data_pipeline, task_id=load_to_gcs_bq.load_product_to_temp, execution_date=20250116T162854, start_date=20250116T163003, end_date=20250116T163007
[2025-01-16T16:30:07.822+0000] {standard_task_runner.py:104} ERROR - Failed to execute job 1947 for task load_to_gcs_bq.load_product_to_temp (400 Error while reading data, error message: Invalid timestamp microseconds value 1737044956452825000 of logical type NONE; in column 'created_at' File: gs://finflow-analytics-data/raw/products/2025-01-16/products.parquet; 606)
[2025-01-16T16:30:07.904+0000] {local_task_job_runner.py:228} INFO - Task exited with return code 1
[2025-01-16T16:30:08.005+0000] {taskinstance.py:2778} INFO - 0 downstream tasks scheduled from follow-on schedule check
