[2025-01-16T02:48:33.393+0000] {taskinstance.py:1159} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: finflow_source_data_pipeline.load_to_gcs_bq.debug_transaction_merge manual__2025-01-16T02:46:20.012580+00:00 [queued]>
[2025-01-16T02:48:33.417+0000] {taskinstance.py:1159} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: finflow_source_data_pipeline.load_to_gcs_bq.debug_transaction_merge manual__2025-01-16T02:46:20.012580+00:00 [queued]>
[2025-01-16T02:48:33.422+0000] {taskinstance.py:1361} INFO - Starting attempt 1 of 1
[2025-01-16T02:48:33.567+0000] {taskinstance.py:1382} INFO - Executing <Task(BigQueryExecuteQueryOperator): load_to_gcs_bq.debug_transaction_merge> on 2025-01-16 02:46:20.012580+00:00
[2025-01-16T02:48:33.639+0000] {standard_task_runner.py:57} INFO - Started process 3570 to run task
[2025-01-16T02:48:33.722+0000] {standard_task_runner.py:84} INFO - Running: ['***', 'tasks', 'run', 'finflow_source_data_pipeline', 'load_to_gcs_bq.debug_transaction_merge', 'manual__2025-01-16T02:46:20.012580+00:00', '--job-id', '1747', '--raw', '--subdir', 'DAGS_FOLDER/finflow.py', '--cfg-path', '/tmp/tmp19t2v9fp']
[2025-01-16T02:48:33.785+0000] {standard_task_runner.py:85} INFO - Job 1747: Subtask load_to_gcs_bq.debug_transaction_merge
[2025-01-16T02:48:34.008+0000] {task_command.py:416} INFO - Running <TaskInstance: finflow_source_data_pipeline.load_to_gcs_bq.debug_transaction_merge manual__2025-01-16T02:46:20.012580+00:00 [running]> on host a445abefd56a
[2025-01-16T02:48:34.406+0000] {taskinstance.py:1662} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='finflow_source_data_pipeline' AIRFLOW_CTX_TASK_ID='load_to_gcs_bq.debug_transaction_merge' AIRFLOW_CTX_EXECUTION_DATE='2025-01-16T02:46:20.012580+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2025-01-16T02:46:20.012580+00:00'
[2025-01-16T02:48:34.416+0000] {bigquery.py:1241} INFO - Executing: 
            SELECT
                'Source table stats' as description,
                'transactions' as table_name,
                COUNT(*) as record_count,
                COUNT(DISTINCT transaction_key) as distinct_keys
            FROM `finflow-analytics-production.finflow_data.src_transactions_temp`
            UNION ALL
            SELECT
                'Target table stats' as description,
                'transactions' as table_name,
                COUNT(*) as record_count,
                COUNT(DISTINCT transaction_key) as distinct_keys
            FROM `finflow-analytics-production.finflow_data.src_transactions`
            
[2025-01-16T02:48:34.425+0000] {crypto.py:82} WARNING - empty cryptography key - values will not be stored encrypted.
[2025-01-16T02:48:34.426+0000] {connection.py:232} WARNING - Connection schemes (type: google_cloud_platform) shall not contain '_' according to RFC3986.
[2025-01-16T02:48:34.433+0000] {base.py:73} INFO - Using connection ID 'google_cloud_default' for task execution.
[2025-01-16T02:48:34.439+0000] {warnings.py:109} WARNING - /home/***/.local/lib/python3.8/site-packages/***/providers/google/cloud/hooks/bigquery.py:2108: AirflowProviderDeprecationWarning: This method is deprecated. Please use `BigQueryHook.insert_job` method.
  warnings.warn(

[2025-01-16T02:48:34.979+0000] {bigquery.py:1595} INFO - Inserting job ***_1736995714966764_60a913c47f739d178b780721686a6545
[2025-01-16T02:48:35.652+0000] {taskinstance.py:1937} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/providers/google/cloud/operators/bigquery.py", line 1249, in execute
    self.job_id = self.hook.run_query(
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/providers/google/cloud/hooks/bigquery.py", line 2241, in run_query
    job = self.insert_job(configuration=configuration, project_id=self.project_id, location=location)
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/providers/google/common/hooks/base_google.py", line 475, in inner_wrapper
    return func(self, *args, **kwargs)
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/providers/google/cloud/hooks/bigquery.py", line 1601, in insert_job
    job_api_repr.result(timeout=timeout, retry=retry)
  File "/home/airflow/.local/lib/python3.8/site-packages/google/cloud/bigquery/job/query.py", line 1580, in result
    do_get_result()
  File "/home/airflow/.local/lib/python3.8/site-packages/google/cloud/bigquery/job/query.py", line 1570, in do_get_result
    super(QueryJob, self).result(retry=retry, timeout=timeout)
  File "/home/airflow/.local/lib/python3.8/site-packages/google/cloud/bigquery/job/base.py", line 922, in result
    return super(_AsyncJob, self).result(timeout=timeout, **kwargs)
  File "/home/airflow/.local/lib/python3.8/site-packages/google/api_core/future/polling.py", line 261, in result
    raise self._exception
google.api_core.exceptions.BadRequest: 400 Unrecognized name: transaction_key; Did you mean transaction_id? at [6:32]

Location: us-central1
Job ID: airflow_1736995714966764_60a913c47f739d178b780721686a6545

[2025-01-16T02:48:35.700+0000] {taskinstance.py:1400} INFO - Marking task as FAILED. dag_id=finflow_source_data_pipeline, task_id=load_to_gcs_bq.debug_transaction_merge, execution_date=20250116T024620, start_date=20250116T024833, end_date=20250116T024835
[2025-01-16T02:48:35.862+0000] {standard_task_runner.py:104} ERROR - Failed to execute job 1747 for task load_to_gcs_bq.debug_transaction_merge (400 Unrecognized name: transaction_key; Did you mean transaction_id? at [6:32]

Location: us-central1
Job ID: airflow_1736995714966764_60a913c47f739d178b780721686a6545
; 3570)
[2025-01-16T02:48:36.151+0000] {local_task_job_runner.py:228} INFO - Task exited with return code 1
[2025-01-16T02:48:37.189+0000] {taskinstance.py:2778} INFO - 0 downstream tasks scheduled from follow-on schedule check
