[2025-01-13T18:36:41.128+0000] {taskinstance.py:1159} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: finflow_source_data_pipeline.load_to_gcs_bq.merge_customer_to_main manual__2025-01-13T18:35:21.340527+00:00 [queued]>
[2025-01-13T18:36:41.258+0000] {taskinstance.py:1159} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: finflow_source_data_pipeline.load_to_gcs_bq.merge_customer_to_main manual__2025-01-13T18:35:21.340527+00:00 [queued]>
[2025-01-13T18:36:41.269+0000] {taskinstance.py:1361} INFO - Starting attempt 1 of 1
[2025-01-13T18:36:41.406+0000] {taskinstance.py:1382} INFO - Executing <Task(BigQueryExecuteQueryOperator): load_to_gcs_bq.merge_customer_to_main> on 2025-01-13 18:35:21.340527+00:00
[2025-01-13T18:36:41.492+0000] {standard_task_runner.py:57} INFO - Started process 12071 to run task
[2025-01-13T18:36:41.553+0000] {standard_task_runner.py:84} INFO - Running: ['***', 'tasks', 'run', 'finflow_source_data_pipeline', 'load_to_gcs_bq.merge_customer_to_main', 'manual__2025-01-13T18:35:21.340527+00:00', '--job-id', '515', '--raw', '--subdir', 'DAGS_FOLDER/finflow.py', '--cfg-path', '/tmp/tmp8uad8sc1']
[2025-01-13T18:36:41.595+0000] {standard_task_runner.py:85} INFO - Job 515: Subtask load_to_gcs_bq.merge_customer_to_main
[2025-01-13T18:36:41.891+0000] {task_command.py:416} INFO - Running <TaskInstance: finflow_source_data_pipeline.load_to_gcs_bq.merge_customer_to_main manual__2025-01-13T18:35:21.340527+00:00 [running]> on host ab4e86dc450e
[2025-01-13T18:36:42.568+0000] {taskinstance.py:1662} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='finflow_source_data_pipeline' AIRFLOW_CTX_TASK_ID='load_to_gcs_bq.merge_customer_to_main' AIRFLOW_CTX_EXECUTION_DATE='2025-01-13T18:35:21.340527+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2025-01-13T18:35:21.340527+00:00'
[2025-01-13T18:36:42.582+0000] {bigquery.py:1241} INFO - Executing: 
MERGE `finflow-analytics-production.finflow_raw.src_customers` T
USING `finflow-analytics-production.finflow_raw.src_customers_temp` S
ON T.customer_key = S.customer_key
WHEN NOT MATCHED THEN
  INSERT (customer_key, customer_id, first_name, last_name, email, phone_number, address, city, state, country, postal_code, customer_segment, customer_since_date, total_accounts, active_accounts, total_transaction_volume, last_transaction_date, is_active, created_at, updated_at, ingestion_timestamp)
  VALUES (S.customer_key, S.customer_id, S.first_name, S.last_name, S.email, S.phone_number, S.address, S.city, S.state, S.country, S.postal_code, S.customer_segment, S.customer_since_date, S.total_accounts, S.active_accounts, S.total_transaction_volume, S.last_transaction_date, S.is_active, S.created_at, S.updated_at, S.ingestion_timestamp)
[2025-01-13T18:36:42.587+0000] {crypto.py:82} WARNING - empty cryptography key - values will not be stored encrypted.
[2025-01-13T18:36:42.596+0000] {connection.py:232} WARNING - Connection schemes (type: google_cloud_platform) shall not contain '_' according to RFC3986.
[2025-01-13T18:36:42.607+0000] {base.py:73} INFO - Using connection ID 'google_cloud_default' for task execution.
[2025-01-13T18:36:42.619+0000] {warnings.py:109} WARNING - /home/***/.local/lib/python3.8/site-packages/***/providers/google/cloud/hooks/bigquery.py:2108: AirflowProviderDeprecationWarning: This method is deprecated. Please use `BigQueryHook.insert_job` method.
  warnings.warn(

[2025-01-13T18:36:43.485+0000] {bigquery.py:1595} INFO - Inserting job ***_1736793403483810_27f5a0ded93c728fec9ae8afd01d28b5
[2025-01-13T18:36:44.570+0000] {taskinstance.py:1937} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/providers/google/cloud/operators/bigquery.py", line 1249, in execute
    self.job_id = self.hook.run_query(
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/providers/google/cloud/hooks/bigquery.py", line 2241, in run_query
    job = self.insert_job(configuration=configuration, project_id=self.project_id, location=location)
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/providers/google/common/hooks/base_google.py", line 475, in inner_wrapper
    return func(self, *args, **kwargs)
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/providers/google/cloud/hooks/bigquery.py", line 1601, in insert_job
    job_api_repr.result(timeout=timeout, retry=retry)
  File "/home/airflow/.local/lib/python3.8/site-packages/google/cloud/bigquery/job/query.py", line 1580, in result
    do_get_result()
  File "/home/airflow/.local/lib/python3.8/site-packages/google/cloud/bigquery/job/query.py", line 1570, in do_get_result
    super(QueryJob, self).result(retry=retry, timeout=timeout)
  File "/home/airflow/.local/lib/python3.8/site-packages/google/cloud/bigquery/job/base.py", line 922, in result
    return super(_AsyncJob, self).result(timeout=timeout, **kwargs)
  File "/home/airflow/.local/lib/python3.8/site-packages/google/api_core/future/polling.py", line 261, in result
    raise self._exception
google.api_core.exceptions.NotFound: 404 Not found: Table finflow-analytics-production:finflow_raw.src_customers was not found in location US

Location: US
Job ID: airflow_1736793403483810_27f5a0ded93c728fec9ae8afd01d28b5

[2025-01-13T18:36:44.726+0000] {taskinstance.py:1400} INFO - Marking task as FAILED. dag_id=finflow_source_data_pipeline, task_id=load_to_gcs_bq.merge_customer_to_main, execution_date=20250113T183521, start_date=20250113T183641, end_date=20250113T183644
[2025-01-13T18:36:44.986+0000] {standard_task_runner.py:104} ERROR - Failed to execute job 515 for task load_to_gcs_bq.merge_customer_to_main (404 Not found: Table finflow-analytics-production:finflow_raw.src_customers was not found in location US

Location: US
Job ID: airflow_1736793403483810_27f5a0ded93c728fec9ae8afd01d28b5
; 12071)
[2025-01-13T18:36:45.150+0000] {local_task_job_runner.py:228} INFO - Task exited with return code 1
[2025-01-13T18:36:45.457+0000] {taskinstance.py:2778} INFO - 0 downstream tasks scheduled from follow-on schedule check
