[2025-01-13T14:35:00.203+0000] {taskinstance.py:1159} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: finflow_source_data_pipeline.load_to_gcs_bq.load_location_to_bq manual__2025-01-13T14:33:47.115125+00:00 [queued]>
[2025-01-13T14:35:00.398+0000] {taskinstance.py:1159} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: finflow_source_data_pipeline.load_to_gcs_bq.load_location_to_bq manual__2025-01-13T14:33:47.115125+00:00 [queued]>
[2025-01-13T14:35:00.406+0000] {taskinstance.py:1361} INFO - Starting attempt 1 of 1
[2025-01-13T14:35:00.625+0000] {taskinstance.py:1382} INFO - Executing <Task(GCSToBigQueryOperator): load_to_gcs_bq.load_location_to_bq> on 2025-01-13 14:33:47.115125+00:00
[2025-01-13T14:35:00.698+0000] {standard_task_runner.py:57} INFO - Started process 2896 to run task
[2025-01-13T14:35:00.737+0000] {standard_task_runner.py:84} INFO - Running: ['***', 'tasks', 'run', 'finflow_source_data_pipeline', 'load_to_gcs_bq.load_location_to_bq', 'manual__2025-01-13T14:33:47.115125+00:00', '--job-id', '283', '--raw', '--subdir', 'DAGS_FOLDER/finflow.py', '--cfg-path', '/tmp/tmpxc3ke1w2']
[2025-01-13T14:35:00.832+0000] {standard_task_runner.py:85} INFO - Job 283: Subtask load_to_gcs_bq.load_location_to_bq
[2025-01-13T14:35:01.505+0000] {task_command.py:416} INFO - Running <TaskInstance: finflow_source_data_pipeline.load_to_gcs_bq.load_location_to_bq manual__2025-01-13T14:33:47.115125+00:00 [running]> on host ab4e86dc450e
[2025-01-13T14:35:02.984+0000] {taskinstance.py:1662} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='finflow_source_data_pipeline' AIRFLOW_CTX_TASK_ID='load_to_gcs_bq.load_location_to_bq' AIRFLOW_CTX_EXECUTION_DATE='2025-01-13T14:33:47.115125+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2025-01-13T14:33:47.115125+00:00'
[2025-01-13T14:35:03.078+0000] {crypto.py:82} WARNING - empty cryptography key - values will not be stored encrypted.
[2025-01-13T14:35:03.091+0000] {connection.py:232} WARNING - Connection schemes (type: google_cloud_platform) shall not contain '_' according to RFC3986.
[2025-01-13T14:35:03.098+0000] {base.py:73} INFO - Using connection ID 'google_cloud_default' for task execution.
[2025-01-13T14:35:03.102+0000] {gcs_to_bigquery.py:376} INFO - Using existing BigQuery table for storing data...
[2025-01-13T14:35:03.856+0000] {gcs_to_bigquery.py:380} INFO - Executing: {'load': {'autodetect': True, 'createDisposition': 'CREATE_IF_NEEDED', 'destinationTable': {'projectId': 'finflow-analytics-production', 'datasetId': 'finflow_raw', 'tableId': 'src_locations'}, 'sourceFormat': 'PARQUET', 'sourceUris': ['gs://finflow-analytics-data/raw/locations/2025-01-13/locations.parquet'], 'writeDisposition': 'WRITE_APPEND', 'ignoreUnknownValues': False, 'schema': {'fields': [{'name': 'location_key', 'type': 'INTEGER', 'mode': 'REQUIRED'}, {'name': 'location_id', 'type': 'STRING', 'mode': 'REQUIRED'}, {'name': 'location_name', 'type': 'STRING', 'mode': 'REQUIRED'}, {'name': 'address', 'type': 'STRING', 'mode': 'REQUIRED'}, {'name': 'city', 'type': 'STRING', 'mode': 'REQUIRED'}, {'name': 'state', 'type': 'STRING', 'mode': 'REQUIRED'}, {'name': 'country', 'type': 'STRING', 'mode': 'REQUIRED'}, {'name': 'country_name', 'type': 'STRING', 'mode': 'REQUIRED'}, {'name': 'country_code', 'type': 'STRING', 'mode': 'REQUIRED'}, {'name': 'postal_code', 'type': 'STRING', 'mode': 'REQUIRED'}, {'name': 'latitude', 'type': 'FLOAT', 'mode': 'REQUIRED'}, {'name': 'longitude', 'type': 'FLOAT', 'mode': 'REQUIRED'}, {'name': 'created_at', 'type': 'TIMESTAMP', 'mode': 'REQUIRED'}, {'name': 'updated_at', 'type': 'TIMESTAMP', 'mode': 'REQUIRED'}, {'name': 'ingestion_timestamp', 'type': 'TIMESTAMP', 'mode': 'REQUIRED'}]}}}
[2025-01-13T14:35:03.884+0000] {bigquery.py:1595} INFO - Inserting job ***_finflow_source_data_pipeline_load_to_gcs_bq_load_location_to_bq_2025_01_13T14_33_47_115125_00_00_6d3bbd2a89c12503d33c7f86ddc77019
[2025-01-13T14:35:04.646+0000] {taskinstance.py:1937} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/providers/google/cloud/transfers/gcs_to_bigquery.py", line 439, in execute
    job.result(timeout=self.result_timeout, retry=self.result_retry)
  File "/home/airflow/.local/lib/python3.8/site-packages/google/cloud/bigquery/job/base.py", line 922, in result
    return super(_AsyncJob, self).result(timeout=timeout, **kwargs)
  File "/home/airflow/.local/lib/python3.8/site-packages/google/api_core/future/polling.py", line 261, in result
    raise self._exception
google.api_core.exceptions.BadRequest: 400 Provided Schema does not match Table finflow-analytics-production:finflow_raw.src_locations. Field region is missing in new schema
[2025-01-13T14:35:04.728+0000] {taskinstance.py:1400} INFO - Marking task as FAILED. dag_id=finflow_source_data_pipeline, task_id=load_to_gcs_bq.load_location_to_bq, execution_date=20250113T143347, start_date=20250113T143500, end_date=20250113T143504
[2025-01-13T14:35:04.891+0000] {standard_task_runner.py:104} ERROR - Failed to execute job 283 for task load_to_gcs_bq.load_location_to_bq (400 Provided Schema does not match Table finflow-analytics-production:finflow_raw.src_locations. Field region is missing in new schema; 2896)
[2025-01-13T14:35:05.050+0000] {local_task_job_runner.py:228} INFO - Task exited with return code 1
[2025-01-13T14:35:05.203+0000] {taskinstance.py:2778} INFO - 0 downstream tasks scheduled from follow-on schedule check
