[2025-01-16T17:32:07.526+0000] {taskinstance.py:1159} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: finflow_source_data_pipeline.load_to_gcs_bq.load_location_to_temp manual__2025-01-16T17:30:57.408098+00:00 [queued]>
[2025-01-16T17:32:07.665+0000] {taskinstance.py:1159} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: finflow_source_data_pipeline.load_to_gcs_bq.load_location_to_temp manual__2025-01-16T17:30:57.408098+00:00 [queued]>
[2025-01-16T17:32:07.671+0000] {taskinstance.py:1361} INFO - Starting attempt 1 of 1
[2025-01-16T17:32:07.838+0000] {taskinstance.py:1382} INFO - Executing <Task(GCSToBigQueryOperator): load_to_gcs_bq.load_location_to_temp> on 2025-01-16 17:30:57.408098+00:00
[2025-01-16T17:32:07.863+0000] {standard_task_runner.py:57} INFO - Started process 3504 to run task
[2025-01-16T17:32:07.919+0000] {standard_task_runner.py:84} INFO - Running: ['***', 'tasks', 'run', 'finflow_source_data_pipeline', 'load_to_gcs_bq.load_location_to_temp', 'manual__2025-01-16T17:30:57.408098+00:00', '--job-id', '2245', '--raw', '--subdir', 'DAGS_FOLDER/finflow.py', '--cfg-path', '/tmp/tmp9ym8m9h0']
[2025-01-16T17:32:07.947+0000] {standard_task_runner.py:85} INFO - Job 2245: Subtask load_to_gcs_bq.load_location_to_temp
[2025-01-16T17:32:08.144+0000] {task_command.py:416} INFO - Running <TaskInstance: finflow_source_data_pipeline.load_to_gcs_bq.load_location_to_temp manual__2025-01-16T17:30:57.408098+00:00 [running]> on host e65a9a79c958
[2025-01-16T17:32:08.673+0000] {taskinstance.py:1662} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='finflow_source_data_pipeline' AIRFLOW_CTX_TASK_ID='load_to_gcs_bq.load_location_to_temp' AIRFLOW_CTX_EXECUTION_DATE='2025-01-16T17:30:57.408098+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2025-01-16T17:30:57.408098+00:00'
[2025-01-16T17:32:08.677+0000] {crypto.py:82} WARNING - empty cryptography key - values will not be stored encrypted.
[2025-01-16T17:32:08.678+0000] {connection.py:232} WARNING - Connection schemes (type: google_cloud_platform) shall not contain '_' according to RFC3986.
[2025-01-16T17:32:08.688+0000] {base.py:73} INFO - Using connection ID 'google_cloud_default' for task execution.
[2025-01-16T17:32:08.690+0000] {gcs_to_bigquery.py:376} INFO - Using existing BigQuery table for storing data...
[2025-01-16T17:32:08.794+0000] {gcs_to_bigquery.py:380} INFO - Executing: {'load': {'autodetect': False, 'createDisposition': 'CREATE_IF_NEEDED', 'destinationTable': {'projectId': 'finflow-analytics-production', 'datasetId': 'finflow_data', 'tableId': 'src_locations_temp'}, 'sourceFormat': 'PARQUET', 'sourceUris': ['gs://finflow-analytics-data/raw/locations/2025-01-16/locations.parquet'], 'writeDisposition': 'WRITE_TRUNCATE', 'ignoreUnknownValues': True, 'schema': {'fields': [{'name': 'location_key', 'type': 'INTEGER', 'mode': 'REQUIRED'}, {'name': 'location_id', 'type': 'INTEGER', 'mode': 'REQUIRED'}, {'name': 'location_name', 'type': 'STRING', 'mode': 'REQUIRED'}, {'name': 'address', 'type': 'STRING', 'mode': 'REQUIRED'}, {'name': 'city', 'type': 'STRING', 'mode': 'REQUIRED'}, {'name': 'state', 'type': 'STRING', 'mode': 'REQUIRED'}, {'name': 'country', 'type': 'STRING', 'mode': 'REQUIRED'}, {'name': 'postal_code', 'type': 'STRING', 'mode': 'REQUIRED'}, {'name': 'latitude', 'type': 'FLOAT', 'mode': 'REQUIRED'}, {'name': 'longitude', 'type': 'FLOAT', 'mode': 'REQUIRED'}, {'name': 'timezone', 'type': 'STRING', 'mode': 'REQUIRED'}, {'name': 'created_at', 'type': 'TIMESTAMP', 'mode': 'REQUIRED'}, {'name': 'updated_at', 'type': 'TIMESTAMP', 'mode': 'REQUIRED'}, {'name': 'ingestion_timestamp', 'type': 'TIMESTAMP', 'mode': 'REQUIRED'}]}}}
[2025-01-16T17:32:08.798+0000] {bigquery.py:1595} INFO - Inserting job ***_finflow_source_data_pipeline_load_to_gcs_bq_load_location_to_temp_2025_01_16T17_30_57_408098_00_00_13f44c1b68fcd5342e4e3d96eab7f530
[2025-01-16T17:32:10.053+0000] {taskinstance.py:1937} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/providers/google/cloud/transfers/gcs_to_bigquery.py", line 439, in execute
    job.result(timeout=self.result_timeout, retry=self.result_retry)
  File "/home/airflow/.local/lib/python3.8/site-packages/google/cloud/bigquery/job/base.py", line 922, in result
    return super(_AsyncJob, self).result(timeout=timeout, **kwargs)
  File "/home/airflow/.local/lib/python3.8/site-packages/google/api_core/future/polling.py", line 261, in result
    raise self._exception
google.api_core.exceptions.BadRequest: 400 Error while reading data, error message: Parquet column 'location_id' has type BYTE_ARRAY which does not match the target cpp_type INT64. File: gs://finflow-analytics-data/raw/locations/2025-01-16/locations.parquet
[2025-01-16T17:32:10.070+0000] {taskinstance.py:1400} INFO - Marking task as FAILED. dag_id=finflow_source_data_pipeline, task_id=load_to_gcs_bq.load_location_to_temp, execution_date=20250116T173057, start_date=20250116T173207, end_date=20250116T173210
[2025-01-16T17:32:10.095+0000] {standard_task_runner.py:104} ERROR - Failed to execute job 2245 for task load_to_gcs_bq.load_location_to_temp (400 Error while reading data, error message: Parquet column 'location_id' has type BYTE_ARRAY which does not match the target cpp_type INT64. File: gs://finflow-analytics-data/raw/locations/2025-01-16/locations.parquet; 3504)
[2025-01-16T17:32:10.114+0000] {local_task_job_runner.py:228} INFO - Task exited with return code 1
[2025-01-16T17:32:10.178+0000] {taskinstance.py:2778} INFO - 0 downstream tasks scheduled from follow-on schedule check
