[2025-01-13T14:05:44.431+0000] {taskinstance.py:1159} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: finflow_source_data_pipeline.load_to_gcs_bq.load_location_to_bq manual__2025-01-13T14:04:46.457822+00:00 [queued]>
[2025-01-13T14:05:44.539+0000] {taskinstance.py:1159} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: finflow_source_data_pipeline.load_to_gcs_bq.load_location_to_bq manual__2025-01-13T14:04:46.457822+00:00 [queued]>
[2025-01-13T14:05:44.542+0000] {taskinstance.py:1361} INFO - Starting attempt 1 of 2
[2025-01-13T14:05:44.666+0000] {taskinstance.py:1382} INFO - Executing <Task(GCSToBigQueryOperator): load_to_gcs_bq.load_location_to_bq> on 2025-01-13 14:04:46.457822+00:00
[2025-01-13T14:05:44.735+0000] {standard_task_runner.py:57} INFO - Started process 1612 to run task
[2025-01-13T14:05:44.750+0000] {standard_task_runner.py:84} INFO - Running: ['***', 'tasks', 'run', 'finflow_source_data_pipeline', 'load_to_gcs_bq.load_location_to_bq', 'manual__2025-01-13T14:04:46.457822+00:00', '--job-id', '179', '--raw', '--subdir', 'DAGS_FOLDER/finflow.py', '--cfg-path', '/tmp/tmph2atv_07']
[2025-01-13T14:05:44.775+0000] {standard_task_runner.py:85} INFO - Job 179: Subtask load_to_gcs_bq.load_location_to_bq
[2025-01-13T14:05:45.119+0000] {task_command.py:416} INFO - Running <TaskInstance: finflow_source_data_pipeline.load_to_gcs_bq.load_location_to_bq manual__2025-01-13T14:04:46.457822+00:00 [running]> on host ab4e86dc450e
[2025-01-13T14:05:45.716+0000] {taskinstance.py:1662} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='finflow_source_data_pipeline' AIRFLOW_CTX_TASK_ID='load_to_gcs_bq.load_location_to_bq' AIRFLOW_CTX_EXECUTION_DATE='2025-01-13T14:04:46.457822+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2025-01-13T14:04:46.457822+00:00'
[2025-01-13T14:05:45.719+0000] {crypto.py:82} WARNING - empty cryptography key - values will not be stored encrypted.
[2025-01-13T14:05:45.730+0000] {connection.py:232} WARNING - Connection schemes (type: google_cloud_platform) shall not contain '_' according to RFC3986.
[2025-01-13T14:05:45.731+0000] {base.py:73} INFO - Using connection ID 'google_cloud_default' for task execution.
[2025-01-13T14:05:45.733+0000] {gcs_to_bigquery.py:376} INFO - Using existing BigQuery table for storing data...
[2025-01-13T14:05:46.175+0000] {gcs_to_bigquery.py:380} INFO - Executing: {'load': {'autodetect': True, 'createDisposition': 'CREATE_IF_NEEDED', 'destinationTable': {'projectId': 'finflow-analytics-production', 'datasetId': 'finflow_raw', 'tableId': 'src_locations'}, 'sourceFormat': 'PARQUET', 'sourceUris': ['gs://finflow-analytics-data/raw/locations/2025-01-13/locations.parquet'], 'writeDisposition': 'WRITE_APPEND', 'ignoreUnknownValues': False}}
[2025-01-13T14:05:46.177+0000] {bigquery.py:1595} INFO - Inserting job ***_finflow_source_data_pipeline_load_to_gcs_bq_load_location_to_bq_2025_01_13T14_04_46_457822_00_00_7f7136ba80977cf8050ab4eccd43e84c
[2025-01-13T14:05:47.079+0000] {taskinstance.py:1937} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/providers/google/cloud/transfers/gcs_to_bigquery.py", line 439, in execute
    job.result(timeout=self.result_timeout, retry=self.result_retry)
  File "/home/airflow/.local/lib/python3.8/site-packages/google/cloud/bigquery/job/base.py", line 922, in result
    return super(_AsyncJob, self).result(timeout=timeout, **kwargs)
  File "/home/airflow/.local/lib/python3.8/site-packages/google/api_core/future/polling.py", line 261, in result
    raise self._exception
google.api_core.exceptions.BadRequest: 400 Provided Schema does not match Table finflow-analytics-production:finflow_raw.src_locations. Field location_key has changed mode from REQUIRED to NULLABLE
[2025-01-13T14:05:47.096+0000] {taskinstance.py:1400} INFO - Marking task as UP_FOR_RETRY. dag_id=finflow_source_data_pipeline, task_id=load_to_gcs_bq.load_location_to_bq, execution_date=20250113T140446, start_date=20250113T140544, end_date=20250113T140547
[2025-01-13T14:05:47.124+0000] {standard_task_runner.py:104} ERROR - Failed to execute job 179 for task load_to_gcs_bq.load_location_to_bq (400 Provided Schema does not match Table finflow-analytics-production:finflow_raw.src_locations. Field location_key has changed mode from REQUIRED to NULLABLE; 1612)
[2025-01-13T14:05:47.150+0000] {local_task_job_runner.py:228} INFO - Task exited with return code 1
[2025-01-13T14:05:47.260+0000] {taskinstance.py:2778} INFO - 0 downstream tasks scheduled from follow-on schedule check
