[2025-01-16T18:59:36.123+0000] {taskinstance.py:1159} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: finflow_source_data_pipeline.data_quality_checks.verify_merge_results_account manual__2025-01-16T18:56:06.587155+00:00 [queued]>
[2025-01-16T18:59:36.240+0000] {taskinstance.py:1159} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: finflow_source_data_pipeline.data_quality_checks.verify_merge_results_account manual__2025-01-16T18:56:06.587155+00:00 [queued]>
[2025-01-16T18:59:36.242+0000] {taskinstance.py:1361} INFO - Starting attempt 1 of 1
[2025-01-16T18:59:36.354+0000] {taskinstance.py:1382} INFO - Executing <Task(BigQueryExecuteQueryOperator): data_quality_checks.verify_merge_results_account> on 2025-01-16 18:56:06.587155+00:00
[2025-01-16T18:59:36.411+0000] {standard_task_runner.py:57} INFO - Started process 1132 to run task
[2025-01-16T18:59:36.432+0000] {standard_task_runner.py:84} INFO - Running: ['***', 'tasks', 'run', 'finflow_source_data_pipeline', 'data_quality_checks.verify_merge_results_account', 'manual__2025-01-16T18:56:06.587155+00:00', '--job-id', '2662', '--raw', '--subdir', 'DAGS_FOLDER/finflow.py', '--cfg-path', '/tmp/tmpv6avikbg']
[2025-01-16T18:59:36.464+0000] {standard_task_runner.py:85} INFO - Job 2662: Subtask data_quality_checks.verify_merge_results_account
[2025-01-16T18:59:36.677+0000] {task_command.py:416} INFO - Running <TaskInstance: finflow_source_data_pipeline.data_quality_checks.verify_merge_results_account manual__2025-01-16T18:56:06.587155+00:00 [running]> on host 1fa24e54c558
[2025-01-16T18:59:37.320+0000] {taskinstance.py:1662} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='finflow_source_data_pipeline' AIRFLOW_CTX_TASK_ID='data_quality_checks.verify_merge_results_account' AIRFLOW_CTX_EXECUTION_DATE='2025-01-16T18:56:06.587155+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2025-01-16T18:56:06.587155+00:00'
[2025-01-16T18:59:37.327+0000] {bigquery.py:1241} INFO - Executing: 
WITH pre_counts AS (
    SELECT 
        'accounts' as table_name,
        COUNT(*) as pre_merge_count
    FROM `finflow-analytics-production.finflow_data.src_accounts`
    WHERE DATE(ingestion_timestamp) < DATE('2025-01-16')
),
post_counts AS (
    SELECT 
        'accounts' as table_name,
        COUNT(*) as post_merge_count
    FROM `finflow-analytics-production.finflow_data.src_accounts`
    WHERE DATE(ingestion_timestamp) <= DATE('2025-01-16')
),
new_records AS (
    SELECT 
        'accounts' as table_name,
        COUNT(*) as new_record_count
    FROM `finflow-analytics-production.finflow_data.src_accounts`
    WHERE DATE(ingestion_timestamp) = DATE('2025-01-16')
)
SELECT
    CASE 
        WHEN post_counts.post_merge_count < pre_counts.pre_merge_count 
        THEN ERROR('Data loss detected in accounts table')
        WHEN post_counts.post_merge_count - pre_counts.pre_merge_count != new_records.new_record_count
        THEN ERROR('Unexpected record count after merge in accounts table')
        ELSE 'Merge validation successful for accounts table'
    END as validation_result
FROM pre_counts
JOIN post_counts ON pre_counts.table_name = post_counts.table_name
JOIN new_records ON pre_counts.table_name = new_records.table_name
[2025-01-16T18:59:37.333+0000] {crypto.py:82} WARNING - empty cryptography key - values will not be stored encrypted.
[2025-01-16T18:59:37.352+0000] {connection.py:232} WARNING - Connection schemes (type: google_cloud_platform) shall not contain '_' according to RFC3986.
[2025-01-16T18:59:37.355+0000] {base.py:73} INFO - Using connection ID 'google_cloud_default' for task execution.
[2025-01-16T18:59:37.370+0000] {warnings.py:109} WARNING - /home/***/.local/lib/python3.8/site-packages/***/providers/google/cloud/hooks/bigquery.py:2108: AirflowProviderDeprecationWarning: This method is deprecated. Please use `BigQueryHook.insert_job` method.
  warnings.warn(

[2025-01-16T18:59:37.946+0000] {bigquery.py:1595} INFO - Inserting job ***_1737053977932070_2e6559b1a0962eeb664b346b217bce06
[2025-01-16T18:59:38.984+0000] {taskinstance.py:1400} INFO - Marking task as SUCCESS. dag_id=finflow_source_data_pipeline, task_id=data_quality_checks.verify_merge_results_account, execution_date=20250116T185606, start_date=20250116T185936, end_date=20250116T185938
[2025-01-16T18:59:39.244+0000] {local_task_job_runner.py:228} INFO - Task exited with return code 0
[2025-01-16T18:59:39.481+0000] {taskinstance.py:2778} INFO - 0 downstream tasks scheduled from follow-on schedule check
