[2025-01-13T13:49:28.562+0000] {taskinstance.py:1159} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: finflow_source_data_pipeline.load_to_gcs_bq.load_transaction_to_bq manual__2025-01-13T13:43:25.319190+00:00 [queued]>
[2025-01-13T13:49:28.582+0000] {taskinstance.py:1159} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: finflow_source_data_pipeline.load_to_gcs_bq.load_transaction_to_bq manual__2025-01-13T13:43:25.319190+00:00 [queued]>
[2025-01-13T13:49:28.583+0000] {taskinstance.py:1361} INFO - Starting attempt 2 of 2
[2025-01-13T13:49:28.608+0000] {taskinstance.py:1382} INFO - Executing <Task(GCSToBigQueryOperator): load_to_gcs_bq.load_transaction_to_bq> on 2025-01-13 13:43:25.319190+00:00
[2025-01-13T13:49:28.624+0000] {standard_task_runner.py:57} INFO - Started process 879 to run task
[2025-01-13T13:49:28.637+0000] {standard_task_runner.py:84} INFO - Running: ['***', 'tasks', 'run', 'finflow_source_data_pipeline', 'load_to_gcs_bq.load_transaction_to_bq', 'manual__2025-01-13T13:43:25.319190+00:00', '--job-id', '120', '--raw', '--subdir', 'DAGS_FOLDER/finflow.py', '--cfg-path', '/tmp/tmpbyp09pmh']
[2025-01-13T13:49:28.643+0000] {standard_task_runner.py:85} INFO - Job 120: Subtask load_to_gcs_bq.load_transaction_to_bq
[2025-01-13T13:49:28.720+0000] {task_command.py:416} INFO - Running <TaskInstance: finflow_source_data_pipeline.load_to_gcs_bq.load_transaction_to_bq manual__2025-01-13T13:43:25.319190+00:00 [running]> on host ab4e86dc450e
[2025-01-13T13:49:28.845+0000] {taskinstance.py:1662} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='finflow_source_data_pipeline' AIRFLOW_CTX_TASK_ID='load_to_gcs_bq.load_transaction_to_bq' AIRFLOW_CTX_EXECUTION_DATE='2025-01-13T13:43:25.319190+00:00' AIRFLOW_CTX_TRY_NUMBER='2' AIRFLOW_CTX_DAG_RUN_ID='manual__2025-01-13T13:43:25.319190+00:00'
[2025-01-13T13:49:28.849+0000] {crypto.py:82} WARNING - empty cryptography key - values will not be stored encrypted.
[2025-01-13T13:49:28.850+0000] {connection.py:232} WARNING - Connection schemes (type: google_cloud_platform) shall not contain '_' according to RFC3986.
[2025-01-13T13:49:28.852+0000] {base.py:73} INFO - Using connection ID 'google_cloud_default' for task execution.
[2025-01-13T13:49:28.853+0000] {gcs_to_bigquery.py:376} INFO - Using existing BigQuery table for storing data...
[2025-01-13T13:49:28.908+0000] {gcs_to_bigquery.py:380} INFO - Executing: {'load': {'autodetect': True, 'createDisposition': 'CREATE_IF_NEEDED', 'destinationTable': {'projectId': 'finflow-analytics-production', 'datasetId': 'finflow_raw', 'tableId': 'src_transactions'}, 'sourceFormat': 'PARQUET', 'sourceUris': ['gs://finflow-analytics-data/raw/transactions/2025-01-13/transactions.parquet'], 'writeDisposition': 'WRITE_APPEND', 'ignoreUnknownValues': False, 'schema': {'fields': [{'name': 'transaction_id', 'type': 'INTEGER', 'mode': 'REQUIRED'}, {'name': 'customer_key', 'type': 'INTEGER', 'mode': 'REQUIRED'}, {'name': 'account_key', 'type': 'INTEGER', 'mode': 'REQUIRED'}, {'name': 'product_key', 'type': 'INTEGER', 'mode': 'REQUIRED'}, {'name': 'location_key', 'type': 'INTEGER', 'mode': 'REQUIRED'}, {'name': 'date_key', 'type': 'INTEGER', 'mode': 'REQUIRED'}, {'name': 'transaction_amount', 'type': 'DECIMAL', 'mode': 'REQUIRED'}, {'name': 'fee_amount', 'type': 'DECIMAL', 'mode': 'REQUIRED'}, {'name': 'transaction_type', 'type': 'STRING', 'mode': 'REQUIRED'}, {'name': 'transaction_status', 'type': 'STRING', 'mode': 'REQUIRED'}, {'name': 'transaction_date', 'type': 'TIMESTAMP', 'mode': 'REQUIRED'}, {'name': 'created_at', 'type': 'TIMESTAMP', 'mode': 'REQUIRED'}, {'name': 'updated_at', 'type': 'TIMESTAMP', 'mode': 'REQUIRED'}, {'name': 'ingestion_timestamp', 'type': 'TIMESTAMP', 'mode': 'REQUIRED'}]}}}
[2025-01-13T13:49:28.910+0000] {bigquery.py:1595} INFO - Inserting job ***_finflow_source_data_pipeline_load_to_gcs_bq_load_transaction_to_bq_2025_01_13T13_43_25_319190_00_00_6742285e54cea9a20e19675260d67500
[2025-01-13T13:49:29.028+0000] {taskinstance.py:1937} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/providers/google/cloud/transfers/gcs_to_bigquery.py", line 381, in execute
    job: BigQueryJob | UnknownJob = self._submit_job(self.hook, job_id)
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/providers/google/cloud/transfers/gcs_to_bigquery.py", line 303, in _submit_job
    return hook.insert_job(
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/providers/google/common/hooks/base_google.py", line 475, in inner_wrapper
    return func(self, *args, **kwargs)
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/providers/google/cloud/hooks/bigquery.py", line 1598, in insert_job
    job_api_repr._begin()
  File "/home/airflow/.local/lib/python3.8/site-packages/google/cloud/bigquery/job/base.py", line 693, in _begin
    api_response = client._call_api(
  File "/home/airflow/.local/lib/python3.8/site-packages/google/cloud/bigquery/client.py", line 808, in _call_api
    return call()
  File "/home/airflow/.local/lib/python3.8/site-packages/google/api_core/retry.py", line 366, in retry_wrapped_func
    return retry_target(
  File "/home/airflow/.local/lib/python3.8/site-packages/google/api_core/retry.py", line 204, in retry_target
    return target()
  File "/home/airflow/.local/lib/python3.8/site-packages/google/cloud/_http/__init__.py", line 494, in api_request
    raise exceptions.from_http_response(response)
google.api_core.exceptions.NotFound: 404 POST https://bigquery.googleapis.com/bigquery/v2/projects/finflow-analytics-production/jobs?prettyPrint=false: Not found: Dataset finflow-analytics-production:finflow_raw
[2025-01-13T13:49:29.043+0000] {taskinstance.py:1400} INFO - Marking task as FAILED. dag_id=finflow_source_data_pipeline, task_id=load_to_gcs_bq.load_transaction_to_bq, execution_date=20250113T134325, start_date=20250113T134928, end_date=20250113T134929
[2025-01-13T13:49:29.060+0000] {standard_task_runner.py:104} ERROR - Failed to execute job 120 for task load_to_gcs_bq.load_transaction_to_bq (404 POST https://bigquery.googleapis.com/bigquery/v2/projects/finflow-analytics-production/jobs?prettyPrint=false: Not found: Dataset finflow-analytics-production:finflow_raw; 879)
[2025-01-13T13:49:29.096+0000] {local_task_job_runner.py:228} INFO - Task exited with return code 1
[2025-01-13T13:49:29.124+0000] {taskinstance.py:2778} INFO - 0 downstream tasks scheduled from follow-on schedule check
