[2025-01-16T18:10:06.301+0000] {taskinstance.py:1159} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: finflow_source_data_pipeline.data_quality_checks.verify_merge_results_location manual__2025-01-16T18:07:01.952921+00:00 [queued]>
[2025-01-16T18:10:06.656+0000] {taskinstance.py:1159} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: finflow_source_data_pipeline.data_quality_checks.verify_merge_results_location manual__2025-01-16T18:07:01.952921+00:00 [queued]>
[2025-01-16T18:10:06.676+0000] {taskinstance.py:1361} INFO - Starting attempt 1 of 1
[2025-01-16T18:10:06.919+0000] {taskinstance.py:1382} INFO - Executing <Task(BigQueryExecuteQueryOperator): data_quality_checks.verify_merge_results_location> on 2025-01-16 18:07:01.952921+00:00
[2025-01-16T18:10:07.124+0000] {standard_task_runner.py:57} INFO - Started process 5491 to run task
[2025-01-16T18:10:07.242+0000] {standard_task_runner.py:84} INFO - Running: ['***', 'tasks', 'run', 'finflow_source_data_pipeline', 'data_quality_checks.verify_merge_results_location', 'manual__2025-01-16T18:07:01.952921+00:00', '--job-id', '2518', '--raw', '--subdir', 'DAGS_FOLDER/finflow.py', '--cfg-path', '/tmp/tmpt_x3qbo0']
[2025-01-16T18:10:07.351+0000] {standard_task_runner.py:85} INFO - Job 2518: Subtask data_quality_checks.verify_merge_results_location
[2025-01-16T18:10:08.232+0000] {task_command.py:416} INFO - Running <TaskInstance: finflow_source_data_pipeline.data_quality_checks.verify_merge_results_location manual__2025-01-16T18:07:01.952921+00:00 [running]> on host e65a9a79c958
[2025-01-16T18:10:09.768+0000] {taskinstance.py:1662} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='finflow_source_data_pipeline' AIRFLOW_CTX_TASK_ID='data_quality_checks.verify_merge_results_location' AIRFLOW_CTX_EXECUTION_DATE='2025-01-16T18:07:01.952921+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2025-01-16T18:07:01.952921+00:00'
[2025-01-16T18:10:09.797+0000] {bigquery.py:1241} INFO - Executing: 
WITH pre_counts AS (
    SELECT 
        'locations' as table_name,
        COUNT(*) as pre_merge_count
    FROM `finflow-analytics-production.finflow_data.src_locations`
    WHERE DATE(ingestion_timestamp) < DATE('2025-01-16')
),
post_counts AS (
    SELECT 
        'locations' as table_name,
        COUNT(*) as post_merge_count
    FROM `finflow-analytics-production.finflow_data.src_locations`
    WHERE DATE(ingestion_timestamp) <= DATE('2025-01-16')
),
new_records AS (
    SELECT 
        'locations' as table_name,
        COUNT(*) as new_record_count
    FROM `finflow-analytics-production.finflow_data.src_locations`
    WHERE DATE(ingestion_timestamp) = DATE('2025-01-16')
)
SELECT
    CASE 
        WHEN post_counts.post_merge_count < pre_counts.pre_merge_count 
        THEN ERROR('Data loss detected in locations table')
        WHEN post_counts.post_merge_count - pre_counts.pre_merge_count != new_records.new_record_count
        THEN ERROR('Unexpected record count after merge in locations table')
        ELSE 'Merge validation successful for locations table'
    END as validation_result
FROM pre_counts
JOIN post_counts ON pre_counts.table_name = post_counts.table_name
JOIN new_records ON pre_counts.table_name = new_records.table_name
[2025-01-16T18:10:09.880+0000] {crypto.py:82} WARNING - empty cryptography key - values will not be stored encrypted.
[2025-01-16T18:10:09.881+0000] {connection.py:232} WARNING - Connection schemes (type: google_cloud_platform) shall not contain '_' according to RFC3986.
[2025-01-16T18:10:09.901+0000] {base.py:73} INFO - Using connection ID 'google_cloud_default' for task execution.
[2025-01-16T18:10:09.967+0000] {warnings.py:109} WARNING - /home/***/.local/lib/python3.8/site-packages/***/providers/google/cloud/hooks/bigquery.py:2108: AirflowProviderDeprecationWarning: This method is deprecated. Please use `BigQueryHook.insert_job` method.
  warnings.warn(

[2025-01-16T18:10:11.854+0000] {bigquery.py:1595} INFO - Inserting job ***_1737051011853032_463ab93b67156a158aa201a5ab310e6d
[2025-01-16T18:10:14.339+0000] {taskinstance.py:1400} INFO - Marking task as SUCCESS. dag_id=finflow_source_data_pipeline, task_id=data_quality_checks.verify_merge_results_location, execution_date=20250116T180701, start_date=20250116T181006, end_date=20250116T181014
[2025-01-16T18:10:14.812+0000] {local_task_job_runner.py:228} INFO - Task exited with return code 0
[2025-01-16T18:10:15.249+0000] {taskinstance.py:2778} INFO - 1 downstream tasks scheduled from follow-on schedule check
